# Hyprpaper Config
# ~/.config/hypr/hyprpaper.conf

# Preload wallpapers
preload = ~/Pictures/wallpapers/void-black.png
preload = ~/Pictures/wallpapers/matte-gradient.png
preload = ~/Pictures/wallpapers/obsidian.png
preload = ~/Pictures/wallpapers/matte-vignette.png
preload = ~/Pictures/wallpapers/gargantua-black.png

# Set initial wallpaper
wallpaper = ,~/Pictures/wallpapers/void-black.png

# IPC for dynamic switching
ipc = true