# Wallpaper list
# Add/remove wallpapers here
WALLPAPERS=(
    "/home/anwar/Pictures/wallpapers/Awesome Minimalist Black Wallpapers - WallpaperAccess.jpg"
    "/home/anwar/Pictures/wallpapers/void-black.png"
    "/home/anwar/Pictures/wallpapers/matte-gradient.png"
    "/home/anwar/Pictures/wallpapers/obsidian.png"
    "/home/anwar/Pictures/wallpapers/matte-vignette.png"
    "/home/anwar/Pictures/wallpapers/gargantua-black.png"
)